<?php

/**
 * @file
 * Contains ike_soldiers_generate_pdf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ike_soldiers_generate_pdf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ike_soldiers_generate_pdf module.
    case 'help.page.ike_soldiers_generate_pdf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates PDFs for Individual Soldiers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ike_soldiers_generate_pdf_theme($existing, $type, $theme, $path) {
  return [
    'soldier__pdf' => [
      'render element' => 'html',
      'template' => 'soldier--pdf',
      'variables' => [
        'variables' => [],
      ],
    ],
  ];
}
