<?php

/**
 * @file
 * Contains ike_email_signup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ike_email_signup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ike_email_signup module.
    case 'help.page.ike_email_signup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow email signup for Constant Contact') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ike_email_signup_theme() {
  return [
    'email_signup_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
